apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
  namespace: ns017
  labels:
    app: dotnet
spec:
  selector:
    matchLabels:
      app: dotnet
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      tolerations:                          # Add this section for tolerations
      - key: "key017"                 # Replace "example-key" with the actual taint key
        operator: "Equal"                  # Operator can be "Equal", "Exists", "DoesNotExist"
        value: "value017"             # Replace "example-value" with the actual taint value
        effect: "NoSchedule"               # Effect can be "NoSchedule", "PreferNoSchedule", "NoExecute"

      containers:
      - name: dotnet
        image: acr017.azurecr.io/dotnet:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dotnet
              key: DB_HOST
        ports:
        - containerPort: 80
          name: dotnet
      imagePullSecrets:
        - name: acrrr-secret
