apiVersion: v1
kind: Service
metadata:
  name: dotnetdemo
  namespace: space  
spec:
  selector:
    app: dotnetdemo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer