apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemo-deployment
  labels:
    app: dotnetdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetdemo
  template:
    metadata:
      labels:
        app: dotnetdemo
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 1818