apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemo-deployment
  namespace: space
  labels:
    app: dotnetdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetdemo
  template:
    metadata:
      labels:
        app: dotnetdemo
    spec:
      containers:
      - name: dotnetdemo
        image: saitejajana/dotnetdemo:2.0
        ports:
        - containerPort: 5000