apiVersion: v1
kind: Service
metadata:
  name: dotnet
  namespace: jana100namespace
spec:
  selector:
    app: dotnet
  type: LoadBalancer
  loadBalancerIP: 10.244.1.1
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: dotnet
    protocol: TCP
    port: 80
    targetPort: 5000
    